---
title: "DepMap_TruSeq_StarF"
author: "bhaas"
date: '2024-02-01'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}

# parse STAR-Fusion predictions based on Illumina reads

StarF_data = read.table("data/DepMap.v1v2mrgd.StarF.consolidated.tsv.gz", header=T, sep="\t", com='') %>%
    rename(sample = X.sample, FusionName = X.FusionName)

StarF_data %>% head()

```

```{r}

# process earlier long-read defined proxy truth set info:

earlier_truth_set_file = "../__bmark_min-1-read/data/preds.collected.gencode_mapped.wAnnot.filt.pass.proxy_assignments.byProgAgree.min_2.truth_set"
earlier_truth_set = read.table(earlier_truth_set_file, header=T, sep="\t") %>% mutate(type='shared')

earlier_truth_set = earlier_truth_set  %>% rowwise() %>% mutate(sample = str_split(proxy_fusion_name, "\\|")[[1]][1])
earlier_truth_set = earlier_truth_set %>% rowwise() %>% mutate(FusionName = str_split(proxy_fusion_name, "\\|")[[1]][2])

earlier_truth_set = earlier_truth_set %>% rowwise() %>% mutate(lex_ordered_fusion_name = paste0(sample, "|", paste0(collapse="--", sort(str_split(FusionName, "--")[[1]])))) 


# unique set
earlier_unique_set_file = "../__bmark_min-1-read/data/preds.collected.gencode_mapped.wAnnot.filt.pass.proxy_assignments.byProgAgree.min_2.unique_set"
earlier_unique_set = read.table(earlier_unique_set_file, header=T, sep="\t") %>% mutate(type='unique')

earlier_unique_set = earlier_unique_set  %>% rowwise() %>% mutate(sample = str_split(proxy_fusion_name, "\\|")[[1]][1])
earlier_unique_set = earlier_unique_set %>% rowwise() %>% mutate(FusionName = str_split(proxy_fusion_name, "\\|")[[1]][2])

earlier_unique_set = earlier_unique_set %>% rowwise() %>% mutate(lex_ordered_fusion_name = paste0(sample, "|", paste0(collapse="--", sort(str_split(FusionName, "--")[[1]])))) 

all_pred_fusions = bind_rows(earlier_truth_set, earlier_unique_set) 

proxy_fusion_name_mapping = all_pred_fusions %>% select(proxy_fusion_name, lex_ordered_fusion_name) %>% unique()

```



```{r}

all_pred_fusions = all_pred_fusions %>% select(lex_ordered_fusion_name, type) %>% unique()

message("num shared fusions: ", earlier_truth_set %>% select(lex_ordered_fusion_name) %>% unique() %>% nrow() )
message("num unique fusions:", earlier_unique_set %>% select(lex_ordered_fusion_name) %>% unique() %>% nrow() )


# num shared:  25419
# num uniquely predicted: 32969

```



```{r}

# add lex_ordered_fusion_name as attribute to STARF data
StarF_data = StarF_data %>% rowwise() %>% 
    mutate(lex_ordered_fusion_name = paste0(sample, "|", paste0(collapse="--", sort(str_split(FusionName, "--")[[1]])))) 


write.table(StarF_data, file="all_STARF_preds.tsv", sep="\t", quote=F, row.names=F)

```


```{r}

# define those fusions in the truth set as illumina-supported or not.

all_pred_fusions_illum_support_indicated = all_pred_fusions %>% 
    mutate(Illumina_support = (lex_ordered_fusion_name %in% StarF_data$lex_ordered_fusion_name))


all_pred_fusions_illum_support_indicated_summary = all_pred_fusions_illum_support_indicated %>% 
    select(lex_ordered_fusion_name, type, Illumina_support) %>% unique() %>% 
    group_by(type, Illumina_support) %>% tally()

all_pred_fusions_illum_support_indicated_summary

# 110 shared and 9 unique have illumina support

```

```{r}

# the uniquely predicted fusions supported by Illumina

all_pred_fusions_illum_support_indicated %>% filter(type=='unique' & Illumina_support) %>% arrange(lex_ordered_fusion_name)


```



```{r}

StarF_overlapping_preds = inner_join(all_pred_fusions_illum_support_indicated, StarF_data, by='lex_ordered_fusion_name', multiple='all')


StarF_overlapping_preds = StarF_overlapping_preds %>% select(lex_ordered_fusion_name, type, sample, FusionName) %>% unique()


StarF_overlapping_preds
```




```{r}

# all Illumina supported ones

full_join(StarF_overlapping_preds,
          all_pred_fusions_illum_support_indicated %>% filter(Illumina_support),
          by=c('lex_ordered_fusion_name',
               'type')
          ) %>% filter(type=='shared')

```


```{r}
# incorporate proxy fusion name

StarF_overlapping_preds = left_join(StarF_overlapping_preds, proxy_fusion_name_mapping, by='lex_ordered_fusion_name')

```



```{r}


StarF_overlapping_preds = StarF_overlapping_preds %>%
    select(proxy_fusion_name, type, sample, FusionName, lex_ordered_fusion_name) %>% unique()

StarF_overlapping_preds

# combining shared and uniquely pred fusions w/ illum support

```





```{r}

full_join(StarF_overlapping_preds,
          all_pred_fusions_illum_support_indicated %>% filter(Illumina_support),
          by=c('lex_ordered_fusion_name','type')
          )

```


```{r}

StarF_overlapping_preds %>% filter(type=="shared")

```

```{r}

StarF_overlapping_preds %>% filter(type=="shared") %>% group_by(lex_ordered_fusion_name) %>% tally() %>% filter(n>1)

```


VCAP|ANO10--SLMAP is found by STARF in both orientations:  SLMAP--ANO10 and ANO10--SLMAP

so, 81 lexically sorted fusions here

```{r}

StarF_overlapping_preds %>% filter(type=="unique")

# 9 of the uniquely pred fusions have illumina support

```



```{r}

write.table(StarF_overlapping_preds, 
            file="StarFusion_Illumina_supported_fusions.tsv", sep="\t", row.names=F, quote=F)


```






