---
title: "examine_resource_usage"
author: "bhaas"
date: '2024-07-23'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}

resource_usage_df = read.csv("resource_usage.stats.tsv", header=T, sep="\t")

resource_usage_df %>% head()

```


```{r}

resource_usage_df %>% ggplot(aes(x=sample, y=exec_time_min)) + geom_col(aes(fill=prog)) + facet_wrap(~prog) +
   theme_bw() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Execution time (minutes)")
   
```

pbfusion = seqtkTask + pbmm2 + pbfusionTAsk

longgf = longGFTask + minimap2Task

fusionseeker = FusionSeekerTask + minimap2Task


```{r}

seqtkTask_df = resource_usage_df %>% filter(prog == 'seqtkTask') %>% rename(seqtk_exec_time = exec_time_min,
                                                                            seqtk_max_mem_GiB = max_memory_GiB)

minimap2Task_df = resource_usage_df %>% filter(prog == 'minimap2Task') %>% rename(mm2_exec_time = exec_time_min,
                                                                               mm2_max_mem_GiB = max_memory_GiB)

pbmm2Task_df = resource_usage_df %>% filter(prog == 'pbmm2') %>% rename(pbmm2_exec_time = exec_time_min,
                                                                     pbmm2_max_mem_GiB = max_memory_GiB)

################################
# sum up relevant workflow parts

# pbfusion

pbfusionTask = left_join( left_join(resource_usage_df %>% filter(prog=='pbfusionTask'), 
                                 seqtkTask_df %>% select(sample, seqtk_exec_time, seqtk_max_mem_GiB), by='sample'),
                       pbmm2Task_df %>% select(sample, pbmm2_exec_time, pbmm2_max_mem_GiB), by='sample' )
                       

pbfusionTask = pbfusionTask %>% rowwise() %>%
    mutate (exec_time_min = exec_time_min + seqtk_exec_time + pbmm2_exec_time,
            max_memory_GiB = max(max_memory_GiB, seqtk_max_mem_GiB, pbmm2_max_mem_GiB) ) 


# longGF

longgfTask = left_join(resource_usage_df %>% filter(prog == 'LongGFTask'),
                       minimap2Task_df %>% select(sample, mm2_exec_time, mm2_max_mem_GiB),
                       by='sample')


longgfTask = longgfTask %>% mutate(exec_time_min = exec_time_min + mm2_exec_time,
                                   max_memory_GiB = max(max_memory_GiB, mm2_max_mem_GiB))


# fusionseeker


FusionSeekerTask = left_join(resource_usage_df %>% filter(prog == 'FusionSeekerTask'),
                       minimap2Task_df %>% select(sample, mm2_exec_time, mm2_max_mem_GiB),
                       by='sample')


FusionSeekerTask = FusionSeekerTask %>% mutate(exec_time_min = exec_time_min + mm2_exec_time,
                                   max_memory_GiB = max(max_memory_GiB, mm2_max_mem_GiB))


```

```{r}

# rebuild resource_usage_df using workflow stats

resource_usage_df  = bind_rows(resource_usage_df %>% filter(prog %in% c('ctat_task', 'JAFFALTask')),
                               pbfusionTask,
                               longgfTask,
                               FusionSeekerTask,
                               
                               )



```


```{r}

resource_usage_df %>% ggplot(aes(x=sample, y=exec_time_min)) + geom_col(aes(fill=prog)) + facet_wrap(~prog) +
   theme_bw() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Execution time (minutes)")
   

```



```{r}

resource_usage_df %>% ggplot(aes(x=sample, y=max_memory_GiB)) + geom_col(aes(fill=prog)) + facet_wrap(~prog) +
   theme_bw() +
   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    ggtitle("Max RAM usage (GiB)")
   
```









