---
title: "ONT_sim_accuracy_analysis"
author: "bhaas"
date: '2024-02-01'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# ONT simulated reads using pbsim3 and R10.4.1 chemistry

Predictions from various methods evaluated on these data and the benchmarking scripts are available here:

https://github.com/fusiontranscripts/LR-FusionBenchmarking/tree/master/simulated_data/ONT_pbsim3_part5

Results are analyzed below:



## fusion pair accuracy

```{r}

max_F1_data = read.table("data/max_F1_summary.tsv", header=T, sep="\t") 

max_F1_data %>% head()

```


```{r}

# barplot

p_barplot = max_F1_data %>% ggplot(aes(x=factor(prog), y=F1)) + theme_bw() +
        geom_bar(stat='identity', position='dodge', aes(fill=sample_count)) +
        facet_grid(vars(analysisType), vars(coverage_level)) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

p_barplot

```


```{r}



mean_samples_F1 = max_F1_data %>% 
    group_by(coverage_level, prog, analysisType) %>%
    summarize(mean_F1 = mean(F1))


mean_samples_F1 %>%
        filter(analysisType %in% c('strict', 'allow_reverse')) %>%
        ggplot() + theme_bw() +
        geom_col(aes(x=prog, y=mean_F1, fill=prog)) +
        facet_grid(vars(analysisType), vars(coverage_level)) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) 


```


## breakpoint results


```{r}
breakpoint_data = read.table("data/breakpoint_maxF1_data.tsv", sep="\t", header=T) 
    


breakpoint_data$coverage_level = factor(breakpoint_data$coverage_level, levels=c('cov5', 'cov50'))

brkpt_accuracy_plot = breakpoint_data %>% ggplot(aes(x=prog, y=F1, fill=sample_count)) + theme_bw() +
        geom_bar(stat='identity', position='dodge', aes(fill=sample_count)) +
        facet_grid(vars(analysisType), vars(coverage_level)) +
        ggtitle("Exact or Fuzzy Breakpoint Detection Accuracy") +
        ylim(0,1) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) 



brkpt_accuracy_plot 

```


```{r}

breakpoint_mean_F1_stats = breakpoint_data %>% group_by(coverage_level, analysisType, prog) %>% 
    summarize(mean_F1 = mean(F1, na.rm=T))


breakpoint_mean_F1_stats %>% ggplot() + theme_bw() +
        geom_col(aes(x=prog, y=mean_F1, fill=prog)) +
        facet_grid(vars(analysisType), vars(coverage_level)) +
        ggtitle("Exact or Fuzzy Breakpoint Detection Accuracy") +
        ylim(0,1)  +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) 


```
                
                
# Combine gene-pair and breakpoint results                
                
                                                                                                                      
```{r}

combined_results = bind_rows(mean_samples_F1,
                             breakpoint_mean_F1_stats)

combined_results %>% head()



```

`

```{r}

combined_results %>%
        filter(analysisType %in% c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt')  ) %>%
        mutate(analysisType = factor(analysisType, 
                            levels=c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt') )) %>%
    ggplot() + theme_bw() +
    geom_jitter(aes(x=analysisType, y=mean_F1, color=prog, shape=prog), width=0.2, height=0, size=rel(2)) +

    facet_wrap(~coverage_level) +
     theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
    

```

```{r}

# just cov50

combined_results %>%
        filter(coverage_level == 'cov50') %>%
        filter(analysisType %in% c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt')  ) %>%
        mutate(analysisType = factor(analysisType, 
                            levels=c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt') )) %>%
    ggplot() + theme_bw() +
    geom_jitter(aes(x=analysisType, y=mean_F1, color=prog, shape=prog), width=0.2, height=0, size=rel(2)) +

    facet_wrap(~coverage_level) +
     theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
    
    

```


```{r}

write.table(combined_results %>%
        #filter(coverage_level == 'cov50') %>%
        filter(analysisType %in% c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt')  ) %>%
        mutate(analysisType = factor(analysisType, 
                            levels=c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt') )),
        
        file = "ONT_sim.mean_F1.combined_results.tsv", sep="\t", row.names=F, quote=F)

```




# Examine PR-AUC

```{r}

mean_AUC_data = read.table("data/mean_PR_AUC_summary.tsv", header=T, sep="\t") 

mean_AUC_data %>% head()

```


```{r}

# barplot

p_barplot = mean_AUC_data %>% ggplot(aes(x=factor(prog), y=mean_AUC)) + theme_bw() +
        geom_bar(stat='identity', position='dodge', aes(fill=prog)) +
        facet_grid(vars(analysisType), vars(coverage_level)) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

p_barplot

```


## PR-AUC breakpoint results


```{r}
breakpoint_AUC_data = read.table("data/breakpoint_all_mean_PR_AUC_data.tsv", sep="\t", header=T) 
    


breakpoint_AUC_data$coverage_level = factor(breakpoint_AUC_data$coverage_level, levels=c('cov5', 'cov50'))

brkpt_AUC_accuracy_plot = breakpoint_AUC_data %>% ggplot(aes(x=prog, y=mean_AUC, fill=prog)) + theme_bw() +
        geom_bar(stat='identity', position='dodge') +
        facet_grid(vars(analysisType), vars(coverage_level)) +
        ggtitle("Exact or Fuzzy Breakpoint Detection Accuracy") +
        ylim(0,1) +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) 



brkpt_AUC_accuracy_plot 

```

# PR-AUC Combine gene-pair and breakpoint results                
                
                                                                                                                      
```{r}

combined_AUC_results = bind_rows(mean_AUC_data,
                             breakpoint_AUC_data)

combined_AUC_results %>% head()



```


```{r}

combined_AUC_results %>%
        filter(analysisType %in% c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt')  ) %>%
        mutate(analysisType = factor(analysisType, 
                            levels=c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt') )) %>%
    ggplot() + theme_bw() +
    geom_jitter(aes(x=analysisType, y=mean_AUC, color=prog, shape=prog), width=0.2, height=0, size=rel(2)) +

    facet_wrap(~coverage_level) +
     theme(axis.text.x = element_text(angle = 90, hjust = 1)) 
    

```

```{r}

write.table(combined_AUC_results %>%
        #filter(coverage_level == 'cov50') %>%
        filter(analysisType %in% c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt')  ) %>%
        mutate(analysisType = factor(analysisType, 
                            levels=c('strict', 'allow_reverse', 'Exact Brkpt', 'Fuzzy Brkpt') )),
        
        file = "ONT_sim.mean_PR_AUC.combined_results.tsv", sep="\t", row.names=F, quote=F)

```
