---
title: "consolidate_fusion_predictions"
author: "bhaas"
date: '2023-09-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(spgs)
```


```{r}

# making output files as:  sample_name + filename_core + operation 
filename_core = "Dondi_overian_CTAT_fusions"


```


```{r}


get_StarF_data = function(starF_preds_file) {
    
    
    starF_data = read.table(starF_preds_file, sep="\t", header=T, stringsAsFactors = F, com='')

    starF_data = starF_data %>% 
        rename(FusionName=X.FusionName) %>%
        select(FusionName, LeftBreakpoint, RightBreakpoint, JunctionReads) %>%
        mutate(JunctionReads = str_split(JunctionReads, ",")) %>%
        unnest(JunctionReads) %>%
        separate(JunctionReads, c('cell_barcode', 'umi', 'read_name'), "\\^") %>%
        mutate(cell_barcode = reverseComplement(cell_barcode, case='upper')) %>%
        mutate(method = "STAR-Fusion")
    
    return(starF_data)
        
}
    

get_FI_data = function(FI_preds_file) {
    
    FI_data = read.table(FI_preds_file, sep="\t", stringsAsFactors = F, header=T, com='')
    
    FI_data = FI_data %>% 
        rename(FusionName=X.FusionName) %>%
        select(FusionName, LeftBreakpoint, RightBreakpoint, JunctionReads) %>%
        mutate(JunctionReads = str_split(JunctionReads, ",")) %>%
        unnest(JunctionReads) %>%
        separate(JunctionReads, c('cell_barcode', 'umi', 'read_name'), "\\^") %>%
        mutate(cell_barcode = reverseComplement(cell_barcode, case='upper')) %>%
        mutate(method="FusionInspector")
    
    return(FI_data)
}

get_Arriba_data = function(arriba_preds_file) {
    
    Arriba_data = read.csv(arriba_preds_file, sep="\t", stringsAsFactors = F, header=T, com='')
    
    Arriba_data$strand1 = sapply(Arriba_data$strand1.gene.fusion., function(x) { str_split(x, "/")[[1]]}[1])
    Arriba_data$strand2 = sapply(Arriba_data$strand2.gene.fusion., function(x) { str_split(x, "/")[[1]]}[1])
    
    Arriba_data = Arriba_data %>% 
        rowwise() %>%
        
        mutate(LeftBreakpointOrig = paste0("chr", breakpoint1, ":", strand1), 
               RightBreakpointOrig = paste0("chr", breakpoint2, ":", strand2) ) %>%
        # deal with gene ordering issue
        mutate(FusionName = ifelse(direction1 == "upstream", paste(X.gene1, gene2, sep="--"), paste(gene2, X.gene1, sep="--"))) %>%
        mutate(LeftBreakpoint = ifelse(direction1 == "upstream", LeftBreakpointOrig, RightBreakpointOrig) ) %>%
        mutate(RightBreakpoint = ifelse(direction1 == "upstream", RightBreakpointOrig, LeftBreakpointOrig) ) %>%
        
        rename(JunctionReads = read_identifiers) %>%
        select(FusionName, LeftBreakpoint, RightBreakpoint, JunctionReads) %>%
        mutate(JunctionReads = str_split(JunctionReads, ",")) %>%
        unnest(JunctionReads) %>%
        separate(JunctionReads, c('cell_barcode', 'umi', 'read_name'), "\\^") %>%
        mutate(cell_barcode = reverseComplement(cell_barcode, case='upper')) %>%
        mutate(method="Arriba")
    
    
    # use of different gene symbols
    Arriba_data$FusionName = str_replace(Arriba_data$FusionName, "RANBP3-DT", "CTC-232P5.1") 
    
    return(Arriba_data)
}


get_ctat_LRF_data = function(ctat_LRF_preds_file) {
    
    ctat_LRF_data = read.table(ctat_LRF_preds_file, sep="\t", stringsAsFactors = F, header=T, com='')  %>%
        rename(FusionName=X.FusionName)
    
    ctat_LRF_ret_data = ctat_LRF_data %>% 
        select(FusionName, LeftBreakpoint, RightBreakpoint, LR_accessions) %>%
        mutate(LR_accessions = str_split(LR_accessions, ",")) %>%
        unnest(LR_accessions) %>%
        separate(LR_accessions, c('cell_barcode', 'umi', 'read_name'), "\\^") %>%
        mutate(method="ctat-LR-fusion")
    
    if ('FFPM' %in% colnames(ctat_LRF_data)) {
        ctat_LRF_FI_data = ctat_LRF_data %>% filter( FFPM != "" ) 
        if (nrow(ctat_LRF_FI_data) > 0) {
                
                ctat_LRF_FI_data = ctat_LRF_FI_data %>%
                    select(FusionName, LeftBreakpoint, RightBreakpoint, JunctionReads) %>%
                    mutate(JunctionReads = str_split(JunctionReads, ",")) %>%
                    unnest(JunctionReads) %>%
                    separate(JunctionReads, c('cell_barcode', 'umi', 'read_name'), "\\^") %>%
                    mutate(cell_barcode = reverseComplement(cell_barcode, case='upper')) %>%
                    mutate(method="FusionInspector")
        
                ctat_LRF_ret_data = bind_rows(ctat_LRF_ret_data, ctat_LRF_FI_data)
        }
    }
    
    return(ctat_LRF_ret_data)
}


get_cell_type_and_umap_info = function(cell_types_file, umap_coords_file) {
    
    cell_type_info = read.table(cell_types_file, header=T, sep="\t", stringsAsFactors = F)
    cell_type_info = cell_type_info %>% mutate(rev_barcode = reverseComplement(barcodes, case='upper'))
    
    # add umap coordinates
    umap_info = read.table(umap_coords_file, header=T, row.names=1, sep=",")
    umap_info$barcodes = rownames(umap_info)

    cell_type_and_umap_info = left_join(cell_type_info, umap_info, by=c('barcodes'='barcodes') )
    
    return(cell_type_and_umap_info)
    
}

```


```{r}

assign_most_agreeable_fusion_name = function(all_fusions) {
    
    all_fusions = all_fusions %>% rowwise() %>% mutate(orig_FusionName = FusionName) %>%
        mutate(lex_sorted_FusionName = paste(collapse="--", sort(str_split(FusionName, "--")[[1]])))
    
    
    use_FusionNames_df = all_fusions %>% select(orig_FusionName, method, lex_sorted_FusionName) %>% unique() %>%
        group_by(lex_sorted_FusionName, orig_FusionName) %>% tally() %>%
        ungroup() %>%
        group_by(lex_sorted_FusionName) %>% arrange(desc(n)) %>% filter(row_number() == 1) %>%
        ungroup() %>% 
        select(lex_sorted_FusionName, orig_FusionName) %>% unique() %>%
        rename(use_FusionName = orig_FusionName)
    
    all_fusions = left_join(all_fusions, use_FusionNames_df, by='lex_sorted_FusionName') %>%
        select(-FusionName) %>%
        rename(FusionName = use_FusionName)
    
    return(all_fusions)
}


```



```{r}

consolidate_data = function(starF_preds_file, FI_preds_file, ctat_LRF_preds_file, 
                            ctat_LRF_FI_preds_file, arriba_preds_file,
                            cell_types_file, umap_coords_file, sample_name) {
    
    starF_data = get_StarF_data(starF_preds_file)
    
    FI_data = get_FI_data(FI_preds_file)
    
    ctat_LRF_data = get_ctat_LRF_data(ctat_LRF_preds_file)
    
    ctat_LRF_FI_data = get_ctat_LRF_data(ctat_LRF_FI_preds_file)
    
    arriba_preds = get_Arriba_data(arriba_preds_file)
    
    all_fusions = bind_rows(starF_data,
                        FI_data,
                        ctat_LRF_data,
                        ctat_LRF_FI_data,
                        arriba_preds)
    
    
    all_fusions = assign_most_agreeable_fusion_name(all_fusions)
    
    print(head(all_fusions))

    cell_type_and_umap_info = get_cell_type_and_umap_info(cell_types_file, umap_coords_file)
    
    all_fusions = left_join(all_fusions, cell_type_and_umap_info, by=c('cell_barcode'='rev_barcode'))
    
    all_fusions = all_fusions %>%  mutate(dataset=sample_name) %>% arrange(FusionName)
    
    all_output_filename = paste(c(sample_name, filename_core, "all_ev_reads.tsv"), collapse='.')        
    message('writing: ', all_output_filename)
    write.table(all_fusions, file=all_output_filename, row.names=F, sep="\t", quote=F)
    
    # remove filtered cells
    all_fusions = all_fusions %>% filter(! is.na(celltype_final))
    all_output_filename = paste(c(sample_name, filename_core, "filtered_cells_only.tsv"), collapse='.')        
    message('writing: ', all_output_filename)
    write.table(all_fusions, file=all_output_filename, row.names=F, sep="\t", quote=F)

    # distill umis
    all_fusions = all_fusions %>% group_by(cell_barcode, FusionName, orig_FusionName, lex_sorted_FusionName, umi, method) %>% filter(row_number()==1) %>% ungroup()
    all_output_filename = paste(c(sample_name, filename_core, "filtered_cells_and_dedup_umis.tsv"), collapse='.')        
    message('writing: ', all_output_filename)
    write.table(all_fusions, file=all_output_filename, row.names=F, sep="\t", quote=F)
    
    # fusion breakpoint cell summary support.
    all_fusions = all_fusions %>% select(FusionName, orig_FusionName, lex_sorted_FusionName, LeftBreakpoint, RightBreakpoint, method, cell_barcode, celltype_final, dataset) %>%
        unique() %>%
        group_by(FusionName, orig_FusionName, lex_sorted_FusionName, LeftBreakpoint, RightBreakpoint, method, celltype_final, dataset) %>% tally(name='cell_counts') %>%
        arrange(desc(cell_counts))
    
    all_output_filename = paste(c(sample_name, filename_core, "filtered_cells_and_dedup_umis.cell_counts_by_method.tsv"), collapse='.')        
    message('writing: ', all_output_filename)
    write.table(all_fusions, file=all_output_filename, row.names=F, sep="\t", quote=F)
    
    
    return(all_fusions)
}

```


```{r}

# Patient1_Om

starF_preds_file = "data/Patient1_Om/Patient1_Om.star-fusion.fusion_predictions.tsv.gz"
FI_preds_file = "data/Patient1_Om/Patient1_Om.finspector.FusionInspector.fusions.tsv.gz"
ctat_LRF_preds_file = "data/Patient1_Om/Patient1_Om.ctat-LR-fusion.fusion_predictions.tsv.gz"
ctat_LRF_FI_preds_file = "data/Patient1_Om/Patient1_Om.ctatLRF_FI.fusion_predictions.tsv.gz"
arriba_preds_file = "data/Patient1_Om/Patient1_Om.arriba.fusions.tsv.gz"
cell_types_file = "data/Patient1_Om/Patient1_Om.bc_to_celltype.tsv.gz"
umap_coords_file = "data/Patient1_Om/Patient1_Om_UMAPcoords.txt"

patient1_Om_fusions = consolidate_data(starF_preds_file, FI_preds_file, ctat_LRF_preds_file,
                                       ctat_LRF_FI_preds_file, arriba_preds_file,
                                       cell_types_file, umap_coords_file,
                                       'Patient1_Om'
                                       )




```


```{r}

# Patient1_Tum

starF_preds_file = "data/Patient1_Tum/Patient1_Tum.star-fusion.fusion_predictions.tsv.gz"
FI_preds_file = "data/Patient1_Tum/Patient1_Tum.finspector.FusionInspector.fusions.tsv.gz"
ctat_LRF_preds_file = "data/Patient1_Tum/Patient1_Tum.ctat-LR-fusion.fusion_predictions.tsv.gz"
ctat_LRF_FI_preds_file = "data/Patient1_Tum/Patient1_Tum.ctatLRF_FI.fusion_predictions.tsv.gz"
arriba_preds_file = "data/Patient1_Tum/Patient1_Tum.arriba.fusions.tsv.gz"
cell_types_file = "data/Patient1_Tum/Patient1_Tum.bc_to_celltype.tsv.gz"
umap_coords_file = "data/Patient1_Tum/Patient1_Tum_UMAPcoords.txt"

patient1_Tum_fusions = consolidate_data(starF_preds_file, FI_preds_file, ctat_LRF_preds_file,
                                        ctat_LRF_FI_preds_file, arriba_preds_file,
                                        cell_types_file, umap_coords_file,
                                        'Patient1_Tum')


```


```{r}

# Patient2_Tum

starF_preds_file = "data/Patient2_Tum/Patient2_Tum.star-fusion.fusion_predictions.tsv.gz"
FI_preds_file = "data/Patient2_Tum/Patient2_Tum.finspector.FusionInspector.fusions.tsv.gz"
ctat_LRF_preds_file = "data/Patient2_Tum/Patient2_Tum.ctat-LR-fusion.fusion_predictions.tsv.gz"
ctat_LRF_FI_preds_file = "data/Patient2_Tum/Patient2_Tum.ctatLRF_FI.fusion_predictions.tsv.gz"
arriba_preds_file = "data/Patient2_Tum/Patient2_Tum.arriba.fusions.tsv.gz"
cell_types_file = "data/Patient2_Tum/Patient2_Tum.bc_to_celltype.tsv.gz"
umap_coords_file = "data/Patient2_Tum/Patient2_Tum_UMAPcoords.txt"


patient2_Tum_fusions = consolidate_data(starF_preds_file, FI_preds_file, ctat_LRF_preds_file,
                                        ctat_LRF_FI_preds_file, arriba_preds_file,
                                        cell_types_file, umap_coords_file,
                                        'Patient2_Tum')


```


```{r}

# Patient3_Om

starF_preds_file = "data/Patient3_Om/Patient3_Om.star-fusion.fusion_predictions.tsv.gz"
FI_preds_file = "data/Patient3_Om/Patient3_Om.finspector.FusionInspector.fusions.tsv.gz"
ctat_LRF_preds_file = "data/Patient3_Om/Patient3_Om.ctat-LR-fusion.fusion_predictions.tsv.gz"
ctat_LRF_FI_preds_file = "data/Patient3_Om/Patient3_Om.ctatLRF_FI.fusion_predictions.tsv.gz"
arriba_preds_file = "data/Patient3_Om/Patient3_Om.arriba.fusions.tsv.gz"
cell_types_file = "data/Patient3_Om/Patient3_Om.bc_to_celltype.tsv.gz"
umap_coords_file = "data/Patient3_Om/Patient3_Om_UMAPcoords.txt"

patient3_Om_fusions = consolidate_data(starF_preds_file, FI_preds_file, ctat_LRF_preds_file,
                                       ctat_LRF_FI_preds_file, arriba_preds_file,
                                       cell_types_file, umap_coords_file,
                                       'Patient3_Om')

```


```{r}

# Patient3_Tum

starF_preds_file = "data/Patient3_Tum/Patient3_Tum.star-fusion.fusion_predictions.tsv.gz"
FI_preds_file = "data/Patient3_Tum/Patient3_Tum.finspector.FusionInspector.fusions.tsv.gz"
ctat_LRF_preds_file = "data/Patient3_Tum/Patient3_Tum.ctat-LR-fusion.fusion_predictions.tsv.gz"
ctat_LRF_FI_preds_file = "data/Patient3_Tum/Patient3_Tum.ctatLRF_FI.fusion_predictions.tsv.gz"
arriba_preds_file = "data/Patient3_Tum/Patient3_Tum.arriba.fusions.tsv.gz"
cell_types_file = "data/Patient3_Tum/Patient3_Tum.bc_to_celltype.tsv.gz"
umap_coords_file = "data/Patient3_Tum/Patient3_Tum_UMAPcoords.txt"


patient3_Tum_fusions = consolidate_data(starF_preds_file, FI_preds_file, ctat_LRF_preds_file,
                                        ctat_LRF_FI_preds_file, arriba_preds_file,
                                        cell_types_file, umap_coords_file,
                                        'Patient3_Tum')

```














