---
title: "eval_before_after_fuzzy_brkpt_filter"
author: "bhaas"
date: '2024-09-16'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}

data = read.csv("data/ctatLRF_fusion_linecounts.txt", sep=" ", header=F)

colnames(data) = c('num_fusions', 'filename')

data = data %>% mutate(num_fusions = num_fusions - 1)

data
```



```{r}

data$core_sample_name = sapply(data$filename, function(x) { str_split(x, "_")[[1]][2]})

data$seqtype = sapply(data$filename, function(x) { str_split(x, "_")[[1]][3]})

data$sample = sapply(data$filename, function(x) { str_split(x, "\\.")[[1]][1]})

data$sample = str_replace(data$sample, "^SGNex_", "")

data = data %>% mutate(fuzzy_restricted = grepl("fuzzy_restricted", filename))

data
```


```{r}

data %>% ggplot(aes(x=sample, y=num_fusions, fill=fuzzy_restricted)) + geom_bar(stat='identity', position='dodge') +
    facet_wrap(~seqtype, scale='free')  + 
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1))



```












